moved iniExpandVariables and iniMergeAndForget functions in os-helpers to use them from other scripts

diff --git a/lib/os-helpers b/lib/os-helpers
--- a/lib/os-helpers
+++ b/lib/os-helpers
@@ -182,3 +182,37 @@ createDatabase() {
   && log "Database created"
   return $?
 }
+
+iniExpandVariables() {
+  [ ! "$1" ] && log 1 iniExpandVariables no ini file specified && return
+  thisini="$1"
+  grep -q '${' $thisini || { log "no var in $thisini, skipping"; return; }
+  log expanding $thisini
+  sed -E "s/($varPattern)/\n\\1\n/g" $TMP.ini \
+  | grep -E --color "$varPattern" | sed -e "s/[{}$]//g" -e "s/|/ /" \
+  | sort -u | while read section variable
+  do
+    value=$(crudget $TMP.ini $section $variable)
+    # echo $section $variable = $value
+    echo "$value" | grep -q "/" \
+    && sed -E -i "s%[$]\{$section\|$variable}%$value%g" $thisini \
+    || sed -E -i "s/[$]\{$section\|$variable}/$value/g" $thisini
+    # grep --color "$section|$variable" $thisini
+    # grep $value $thisini
+  done
+}
+
+iniMergeAndForget() {
+  [ ! "$3" ] && log 1 "usage iniMergeAndForget ini section variable" && return 1
+  thisini=$1
+  section=$2
+  variable=$3
+  file=$(crudget $thisini $section $variable)
+  [ ! -e "$file" ] && log 2 "file $file not found" && return 2
+
+  log mergin $common
+  crudmerge $thisini $file
+  crudini --del $thisini $section $variable
+  sed -i "s/Include_/Include-/" $thisini
+  iniExpandVariables $thisini
+}
